In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.dot(a,b)
c

array([[19, 22],
       [43, 50]])

In [3]:
d = np.dot(b,a)
d

array([[23, 34],
       [31, 46]])

In [4]:
a = np.array([[1,2],[3,4]])
e = np.array([5,6])
f = np.dot(a,e)
f

array([17, 39])

In [7]:
a = np.array([[1,2],[3,4]])
e = np.array([5,6])
a*e

array([[ 5, 12],
       [15, 24]])

In [8]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8,9],
              [10,11,12]])
c = np.cross(A, B)
c

array([[-6, 12, -6],
       [-6, 12, -6]])

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
C = np.cross(a, b)
C

array([-3,  6, -3])