In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5])
a.dtype

dtype('int32')

In [6]:
myarr = np.array([[3,6,32,7]], np.int64)
myarr

array([[ 3,  6, 32,  7]], dtype=int64)

In [7]:
myarr[0, 1]

6

In [8]:
myarr.shape

(1, 4)

In [12]:
myarr[0, 1]

6

In [15]:
myarr[0, 1] = 60000

In [16]:
myarr

array([[    3, 60000,    32,     7]], dtype=int64)

Array Creation: Conversion from other Python structure

In [17]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [18]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [19]:
listarray.dtype

dtype('int32')

In [20]:
listarray.shape

(3, 3)

In [21]:
listarray.size

9

In [22]:
np.array({34,23,23})

array({34, 23}, dtype=object)