Importing Library

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7], order = 'F')
a

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b.size

6

In [6]:
b.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
flatten1 = b.ravel()
flatten1

array([1, 2, 3, 4, 5, 6])

In [8]:
flatten2 = b.flatten()
flatten2

array([1, 2, 3, 4, 5, 6])

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
reshape_c = b.reshape(3, 2, order = 'C')
reshape_c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
reshape_r = b.reshape(3, 2, order = 'F')
reshape_r

array([[1, 5],
       [4, 3],
       [2, 6]])

In [12]:
c = np.array([1,2,3,4,5,6])
c

array([1, 2, 3, 4, 5, 6])

In [13]:
c.reshape(3, 2, order = 'F')

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
c[::5]

array([1, 6])

In [15]:
e = np.array([[10,20,30,40,50],
              [60,70,80,90,100],
              [110,120,130,140,150],
              [160,170,180,190,200]])
e

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [17]:
second_row = e[:,3:4]
second_row

array([[ 40],
       [ 90],
       [140],
       [190]])

In [18]:
last_2rows = e[-2:,:]
last_2rows

array([[110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [20]:
selected = np.array([e[0, :]])
s2 = np.array([e[2,1]])
print(selected)
print(s2)

[[10 20 30 40 50]]
[120]
