Importing Library

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7], order = 'F')
a

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b.size

6

In [5]:
b.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
flatten1 = b.ravel()
flatten1

array([1, 2, 3, 4, 5, 6])

In [7]:
flatten2 = b.flatten()
flatten2

array([1, 2, 3, 4, 5, 6])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
reshape_c = b.reshape(3, 2, order = 'C')
reshape_c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
reshape_r = b.reshape(3, 2, order = 'F')
reshape_r

array([[1, 5],
       [4, 3],
       [2, 6]])

In [11]:
c = np.array([1,2,3,4,5,6])
c

array([1, 2, 3, 4, 5, 6])

In [12]:
c.reshape(3, 2, order = 'F')

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
c[::5]

array([1, 6])

In [14]:
e = np.array([[10,20,30,40,50],
              [60,70,80,90,100],
              [110,120,130,140,150],
              [160,170,180,190,200]])
e

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [15]:
second_row = e[:,3:4]
second_row

array([[ 40],
       [ 90],
       [140],
       [190]])

In [16]:
last_2rows = e[-2:,:]
last_2rows

array([[110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

In [17]:
selected = np.array([e[0, :]])
s2 = np.array([e[2,1]])
print(selected)
print(s2)

[[10 20 30 40 50]]
[120]


In [18]:
np.empty((3, 3), dtype = int)

array([[   0,    1,    0],
       [ 581, 1520,    0],
       [ 768,  581,    0]])

In [19]:
np.zeros((3, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
np.ones((3, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
np.eye(4, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [22]:
np.full((3, 2), 3, dtype = float)

array([[3., 3.],
       [3., 3.],
       [3., 3.]])

In [23]:
arr = np.random.randint(1, 100, 5)
arr

array([43, 86, 37, 12, 57])

In [24]:
arr2 = np.random.uniform(1, 100, 5)
arr2

array([53.3080985 , 12.99175222, 80.98435989, 97.89190049, 25.68769554])

In [25]:
normally = np.random.normal(50, 10, 5)
normally

array([63.34284886, 40.06908891, 44.78093795, 34.13857758, 62.46342545])

In [26]:
normally.std()

11.877678704512013

In [27]:
wait = np.array([45.74176736, 42.58559161, 41.56403124, 47.88771798, 52.98868176])

In [28]:
arr3 = np.arange(1, 10, 2)
arr3

array([1, 3, 5, 7, 9])

In [29]:
arr4 = np.linspace(1, 100, endpoint = False)
arr4

array([ 1.  ,  2.98,  4.96,  6.94,  8.92, 10.9 , 12.88, 14.86, 16.84,
       18.82, 20.8 , 22.78, 24.76, 26.74, 28.72, 30.7 , 32.68, 34.66,
       36.64, 38.62, 40.6 , 42.58, 44.56, 46.54, 48.52, 50.5 , 52.48,
       54.46, 56.44, 58.42, 60.4 , 62.38, 64.36, 66.34, 68.32, 70.3 ,
       72.28, 74.26, 76.24, 78.22, 80.2 , 82.18, 84.16, 86.14, 88.12,
       90.1 , 92.08, 94.06, 96.04, 98.02])

In [30]:
arr = [10, 20, 30, 40, 50]
random_choice = np.random.choice(arr)
random_choice

20

In [31]:
a = np.array([[1,2],[3,4]])
a * 2

array([[2, 4],
       [6, 8]])

In [32]:
b = np.array([[5,6],[7,8]])
a * b

array([[ 5, 12],
       [21, 32]])

In [33]:
g = np.array([[1,2],[3,4]])
h = np.array([[5,6],[7,8]])
i = np.dot(g,h)
i

array([[19, 22],
       [43, 50]])

In [34]:
j = np.dot(h,g)
j

array([[23, 34],
       [31, 46]])

In [35]:
k = np.array([5,6])
l = np.dot(g,k)
l

array([17, 39])

In [37]:
g * k

array([[ 5, 12],
       [15, 24]])

In [39]:
m = np.array([1,2,3])
n = np.array([4,5,6])
cr = np.cross(m,n)
cr

array([-3,  6, -3])

In [40]:
o = np.array([[1,2,3],
              [4,5,6]])
p = np.array([[7,8,9],
              [10,11,12]])
cross_product = np.cross(o,p)
cross_product

array([[-6, 12, -6],
       [-6, 12, -6]])