In [1]:
import numpy as np

Defining an 2-D array

In [2]:
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]

In [3]:
b = [[9,6,3],
     [8,5,2],
     [7,4,1]]

In [4]:
c = np.array(a)
d = np.array(b)

In [5]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
d

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

Dotproduct and Cross Product of N-D array

In [7]:
dotproduct = np.dot(a, b)
crossproduct = np.cross(a, b)

In [8]:
print(f'Dot Product of {a} and {b}: \n{dotproduct}')
print('--------------------------------------------------------------------')
print(f'Cross Product of {a} and {b}: \n{crossproduct}')

Dot Product of [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and [[9, 6, 3], [8, 5, 2], [7, 4, 1]]: 
[[ 46  28  10]
 [118  73  28]
 [190 118  46]]
--------------------------------------------------------------------
Cross Product of [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and [[9, 6, 3], [8, 5, 2], [7, 4, 1]]: 
[[-12  24 -12]
 [-20  40 -20]
 [-28  56 -28]]
