In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
a.dtype

dtype('int32')

In [3]:
myarr = np.array([[3,6,32,7]], np.int64)
myarr

array([[ 3,  6, 32,  7]], dtype=int64)

In [4]:
myarr[0, 1]

6

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr[0, 1]

6

In [7]:
myarr[0, 1] = 60000

In [8]:
myarr

array([[    3, 60000,    32,     7]], dtype=int64)

Array Creation: Conversion from other Python structure

In [9]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [15]:
zeros = np.zeros((2, 5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.shape

(2, 5)

In [20]:
rng = np.arange(15)

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
rng.dtype

dtype('int32')

In [23]:
lspace = np.linspace(1,5,12)

In [24]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
emp = np.empty((4,6))

In [26]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.24610994e-306, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 8.90104239e-307, 6.89804132e-307,
        1.33512376e-306, 6.89806849e-307, 9.34609790e-307],
       [1.69121096e-306, 1.05700515e-307, 2.04712906e-306,
        7.56589622e-307, 1.11258277e-307, 8.90111708e-307]])

In [27]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [28]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
ide.shape

(45, 45)

In [30]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [32]:
arr1 = arr.reshape(4, 10)
arr1

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [33]:
arr1.ravel()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [34]:
arr1.shape

(4, 10)

In [35]:
arr.shape

(40,)

In [36]:
x = [[1,2,3],[4,5,6],[7,1,0]]
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [37]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [38]:
ar.sum(axis = 0)

array([12,  8,  9])

In [39]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [40]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [41]:
ar.flat

In [42]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [43]:
ar.ndim

2

In [44]:
ar.size

9

In [45]:
ar.nbytes

36

In [46]:
one = np.array([1,3,4,634,2])

In [48]:
one.argmax()

3

In [49]:
one.argmin()

0

In [50]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [52]:
ar.argmin()

8

In [53]:
ar.argmax()

6

In [54]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [55]:
ar.argmax(axis = 0)

array([2, 1, 1], dtype=int64)

In [56]:
ar.argmax(axis = 1)

array([2, 2, 0], dtype=int64)

In [57]:
ar.argmin(axis = 0)

array([0, 2, 2], dtype=int64)

In [58]:
ar.argmin(axis = 1)

array([0, 0, 2], dtype=int64)

In [59]:
ar.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [60]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [62]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [63]:
ar.reshape((9, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
ar2 = np.array([[1,2,1],
                [4,0,6],
                [8,1,0]])
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [66]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])