Importing Numpy to perform all functions of Numpy

In [1]:
import numpy as np

Basic Operations of Numpy with array

In [2]:
a = np.array([1, 2, 3, 4, 5])
a.dtype

dtype('int32')

In [3]:
myarr = np.array([[3,6,32,7]], np.int64)
myarr

array([[ 3,  6, 32,  7]], dtype=int64)

In [4]:
myarr[0, 1]

6

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr[0, 1]

6

In [7]:
myarr[0, 1] = 60000

In [8]:
myarr

array([[    3, 60000,    32,     7]], dtype=int64)

Array Creation: Conversion from other Python structure

In [9]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({34,23,23})

array({34, 23}, dtype=object)

Generating an array of zeros of particular number of rows and columns

In [15]:
zeros = np.zeros((2, 5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

To check the shape of an array

In [18]:
zeros.shape

(2, 5)

To create 1-D array using arrange function

In [19]:
rng = np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
rng.dtype

dtype('int32')

To create 1-D array using linespace funtion

In [22]:
lspace = np.linspace(1,5,12)

In [23]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

To create 1-D or N-D array using empty function

In [24]:
emp = np.empty((4,6))

In [25]:
emp

array([[2.56761491e-312, 2.41907520e-312, 6.79038654e-313,
        6.79038653e-313, 2.37663529e-312, 2.05833592e-312],
       [2.41907520e-312, 2.56761491e-312, 1.93101617e-312,
        1.08221785e-312, 1.14587773e-312, 1.08221785e-312],
       [9.33678148e-313, 1.97345609e-312, 9.33678148e-313,
        2.33419537e-312, 9.76118064e-313, 2.33419537e-312],
       [1.14587773e-312, 8.70018275e-313, 2.31297541e-312,
        2.05833592e-312, 2.41907520e-312, 3.20558931e-317]])

To copy another function using empty like function

In [26]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

To create an identity matrix array

In [27]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
ide.shape

(45, 45)

To create an array of particular range

In [29]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

To reshape an array

In [30]:
arr1 = arr.reshape(4, 10)
arr1

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

To reshape an 2-D array into 1-D array

In [31]:
arr1.ravel()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [32]:
arr1.shape

(4, 10)

In [33]:
arr.shape

(40,)

To create 2-D array

In [34]:
x = [[1,2,3],[4,5,6],[7,1,0]]
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [35]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

To find out sum along Axis = 0 which means sum along rows

In [36]:
ar.sum(axis = 0)

array([12,  8,  9])

To find out sum along Axis = 1 which means sum along columns

In [37]:
ar.sum(axis = 1)

array([ 6, 15,  8])

To transpose an array which means row into column and column into row

In [38]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [39]:
ar.flat

In [40]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


To find out dimensions of an array

In [41]:
ar.ndim

2

To find out an size of an array

In [42]:
ar.size

9

To find out number of bytes in array

In [43]:
ar.nbytes

36

In [44]:
one = np.array([1,3,4,634,2])

To find out index value of maximum value

In [45]:
one.argmax()

3

To find out index value of minimum value

In [46]:
one.argmin()

0

To find out index values of items present in array in ascending values

In [47]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
ar.argmin()

8

In [50]:
ar.argmax()

6

In [51]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [52]:
ar.argmax(axis = 0)

array([2, 1, 1], dtype=int64)

In [53]:
ar.argmax(axis = 1)

array([2, 2, 0], dtype=int64)

In [54]:
ar.argmin(axis = 0)

array([0, 2, 2], dtype=int64)

In [55]:
ar.argmin(axis = 1)

array([0, 0, 2], dtype=int64)

In [56]:
ar.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [57]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [58]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [59]:
ar.reshape((9, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [60]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [61]:
ar2 = np.array([[1,2,1],
                [4,0,6],
                [8,1,0]])
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

To find out the sum of two corresponding array values in two different array

In [62]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

To find out the product of twom corresponding array values in two different array

In [63]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

To find out squareroot of an array

In [64]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [65]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

To find out the sum of all items in arrays

In [66]:
ar.sum()

29

To find out minimum value in given array

In [67]:
ar.min()

0

To find out maximum value i given array

In [68]:
ar.max()

7

To find out the row number and column number for particular item in array

In [69]:
np.where(ar > 5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

To find out data type of indexing values

In [70]:
type(np.where(ar > 5))

tuple

To find out the count of non-zero elements in array

In [71]:
np.count_nonzero(ar)

8

To find out thr row number and column number of an array

In [72]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [73]:
ar[1, 2] = 0
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

To check out the byte memory is less in case of numpy than other libraries

In [74]:
import sys

In [75]:
py_ar = [0, 4, 55, 2]
np_ar = np.array(py_ar)

Size according to sys library

In [76]:
sys.getsizeof(1) * len(py_ar)

112

Size according to numpy library

In [77]:
np_ar.itemsize * np_ar.size

16